title: Reuzenarbeid
base_url: https://allmaps.org/reuzenarbeid/

# Preferred map tiles
# tile_url: https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}
tile_url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}'
# tile_url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}'

# Preferred IIIF viewer
viewer_base_url: https://universalviewer.io/uv.html?manifest=
# viewer_base_url: https://projectmirador.org/embed/?manifest= # Canvas selection impossible

# IIIF Server settings
image_base_url: https://dlc.services/iiif-img/7/
manifest_base_url: https://allmaps.org/reuzenarbeid/manifests/

# Allmaps
allmaps_api_base: https://annotations.allmaps.org/manifests/
allmaps_viewer_base: https://viewer.allmaps.org/#data=data:text/x-url,

collections:
  projects:
    output: false
